@api = http://localhost:3000/clientes
GET {{api}}

###
POST {{api}}
Content-Type: application/json

{
    "NroDocumento":"121241",
    "ApellidosNombres":"Perez Pizarro Fernando",
    "FechaHoraRegistro": "2024-03-08 00:53:12.157"
}


###
GET {{api}}/12

### Deleting a product

DELETE  {{api}}/43

###
GET {{api}}/count

###
PUT  {{api}}/12

Content-Type: application/json

{
    "NroDocumento": "07457632",
    "ApellidosNombres":"Snadyer lopez perez",
    "FechaHoraRegistro":"2024-03-05T04:08:05.177Z"
}
